CREATE TABLE IF NOT EXISTS pet (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  code VARCHAR(100),
  type VARCHAR(100),
  fur_color VARCHAR(100),
  country VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS type (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS fur_color (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS country (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);